"ui.menu" = { bg = "black" }
"ui.menu.selected" = { bg = "black" }
"ui.menu.scroll" = { fg = "black", bg = "black" }
"ui.window" = { fg = "black" }
"ui.linenr" = { fg = "black" }
"ui.linenr.selected" = { fg = "white" }
"ui.popup" = { fg = "white", bg = "black" }
"ui.popup.info" = { fg = "white", bg = "black2" }
"ui.selection" = { fg = "black", bg = "blue" }
"ui.selection.primary" = { modifiers = ["reversed"] }
"comment" = { fg = "black" }
"ui.statusline" = { fg = "white", bg = "black2" }
"ui.statusline.inactive" = { fg = "black", bg = "black2" }
"ui.help" = { fg = "white", bg = "black2" }
"ui.cursor" = { modifiers = ["reversed"] }
"ui.virtual.ruler" = { bg = "#1a1a1a" }
"variable" = "white"
"variable.builtin" = "yellow"
"constant.numeric" = "yellow"
"constant" = "yellow"
"attributes" = "blue"
"type" = "cyan"
"ui.cursor.match" = { fg = "cyan", modifiers = ["underlined"] }
"string" = "green"
"variable.other.member" = "blue"
"constant.character.escape" = "yellow"
"function" = "yellow"
"function.builtin" = "blue"
"function.method" = "blue"
"constructor" = "blue"
"special" = "yellow"
"keyword" = "magenta"
"keyword.control.repeat" = "magenta"
"label" = "magenta"
"namespace" = "blue"
"diff.plus" = "green"
"diff.delta" = "yellow"
"diff.minus" = "red"
diagnostic = { modifiers = ["underlined"] }
"ui.gutter" = { bg = "black2" }
info = "blue"
hint = "white"
debug = "white"
warning = "yellow"
error = "red"
"ui.virtual.whitespace" = { fg = "black" }
"markup.heading.marker" = "#00b2ff"
"markup.heading.1" = "#00b2ff"
"markup.heading.2" = "#00b2ff"
"markup.heading.3" = "#00b2ff"
"markup.heading.4" = "#00b2ff"
"markup.heading.5" = "#00b2ff"
"markup.heading.6" = "#00b2ff"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.underline.link" = { fg = "#008a88", modifiers = ["underlined"] }
"markup.raw.inline" = { bg = "#303030", fg = "#ff4f58" }
"markup.list.unnumbered" = "black"
"markup.list.numbered" = "black"
"markup.raw.block" = { fg = "black" }
"markup.link.url" = { fg = "#008a88", modifiers = ["underlined"] }
"markup.link.label" = { fg = "#00b255" }
"markup.link.text" = { fg = "#00b255" }


[palette.normal]

background = "#171717"
foreground = "#C5C8C6"
black = "#282a2e"
blue = "#8056FF"
cyan = "#04D7D7"
green = "#31BB71"
magenta = "#ED61D7"
red = "#D74E6F"
yellow = "#D3E561"
white = "#C5C8C6"

